### ISSUE TITLE
An initial to-do 

### ISSUE THREAD

**Issue by chrishavlin** [data-exp-lab/yt-napari#1]
The repository is initialized!

Things to do in the near term include: 

Re-implemt a yt-reader based on the prototype ([napari-ytschema](https://github.com/data-exp-lab/github.com/data-exp-lab/napari-ytschema)). Initially, we should have a more stripped down version of it. Still want to parse a json, but for now let's use a more self-contained json validation approach:

- [x] write a basic pydantic model to validate the parameters we need to load and extract data
- [x] write a separate ingestion routine to actually run the yt code based on the validated json
- [x] do the above in such a way that down the line we can easy switch over to use `analysis_schema` 

    
Initial test suite:

- [x] The standard reader test will be easy: just check that a json is correctly identified as readable. 
- [x] Would be good to include an actual load test, but need to decide on the best way to include a yt dataset for testing.

Other items:

- [x]  check on how the manifest displayname is used, currently set to default FooBar (see src/yt_napari/napari.yaml) -- this `display_name` is what would be displayed in the plugin dropdown menu. Since the initial plugin is only a reader, this will not be used anywhere, but I updated it to `yt-napari` for now. It **will** be used for the widget, so may want to update it later.
- [x] update the github workflows. Currently we have the default from napari's npe2 cookiecutter, a test and deploy workflow (deploy only happens when new version tags are pushed). Would be good to add some others: linting, package manifest checks, etc.

**Comment by matthewturk** [comment]
For the first item, do you see that as being something fed into `yt.load` or something that works at a lower level in yt?

**Comment by chrishavlin** [comment]
> For the first item, do you see that as being something fed into `yt.load` or something that works at a lower level in yt?

My initial thought is to have the same behavior as the prototype, which would be a `yt.load` followed by extracting data for a field on a uniform grid. So in the json you'd specify the data set, fieldname, bounds of a selection and resolution.

**Comment by matthewturk** [comment]
That sounds perfect.

**Comment by chrishavlin** [comment]
Update: most of these items were taken care of in #2!

**Comment by chrishavlin** [comment]
github workflows updated in #4

**Comment by chrishavlin** [comment]
oops, didn't mean to close right away. I'll re-open this until I create a new issue that is more of a release roadmap.

**Comment by chrishavlin** [comment]
#6 addressed the `analysis_schema` point and more clearly defined the json validation and processing steps, so it should be easy to pop in the `analysis_schema` whenever ready.

**Comment by chrishavlin** [comment]
I'm going to close this now that https://github.com/data-exp-lab/yt-napari/issues/7 is live.
